import {Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});
import SessionWrapper from '@/components/common/SessionWrapper'
import {AppKit} from '@/context/web3modal'

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}) {
	return (
		<SessionWrapper>
			<AppKit>
				<html lang="en">
				<body className={inter.className}>{children}</body>
				</html>
			</AppKit>
		</SessionWrapper>
	);
}
