export const developerPositions = [
	"Frontend Developer",
	"Backend Developer",
	"Full Stack Developer",
	"Mobile App Developer",
	"DevOps Engineer",
	"Software Engineer",
	"Data Scientist",
	"Machine Learning Engineer",
	"Blockchain Developer",
	"Game Developer",
	"Embedded Systems Developer",
	"Cloud Engineer",
	"Database Administrator",
	"Site Reliability Engineer (SRE)",
	"Security Engineer",
	"UI/UX Developer",
	"Web Developer",
	"AR/VR Developer",
	"AI Developer",
	"Big Data Engineer",
	"Systems Developer",
	"Application Developer",
	"Software Architect",
	"Network Engineer",
	"IT Support Engineer"
];


export const techIndustries = [
	"Artificial Intelligence",
	"Blockchain",
	"Cybersecurity",
	"Cloud Computing",
	"Internet of Things (IoT)",
	"Big Data Analytics",
	"E-commerce",
	"Fintech",
	"Augmented Reality (AR) & Virtual Reality (VR)",
	"Robotics",
	"5G Technology",
	"Software Development",
	"EdTech",
	"HealthTech",
	"InsurTech",
	"Biotech",
	"Quantum Computing",
	"Autonomous Vehicles",
	"Green Technology",
	"Digital Marketing",
	"Social Media",
	"Gaming",
	"Wearable Technology",
	"LegalTech",
	"PropTech",
	"Supply Chain Tech"
];
