export const filterOptions = [
  {
    id: "country",
    label: "Country",
    datalistOptions: [
      "United States",
      "Canada",
      "Brazil",
      "United Kingdom",
      "Germany",
      "France",
      "Italy",
      "Spain",
      "Australia",
      "Japan",
      "China",
      "India",
      "Russia",
      "Mexico",
      "South Africa",
      "Nigeria",
      "Egypt",
      "Turkey",
      "Saudi Arabia",
      "Argentina",
      "Chile",
      "Colombia",
      "South Korea",
      "Indonesia",
      "Vietnam",
      "Thailand",
      "Malaysia",
      "Philippines",
      "Singapore",
      "New Zealand",
      "Sweden",
      "Norway",
      "Denmark",
      "Finland",
      "Netherlands",
      "Belgium",
      "Switzerland",
      "Austria",
      "Poland",
      "Czech Republic",
      "Hungary",
      "Greece",
      "Portugal",
      "Ireland",
      "Iceland",
      "Israel",
      "United Arab Emirates",
      "Qatar",
      "Kuwait",
      "Pakistan",
      "Bangladesh",
    ],
  },
  {
    id: "city",
    label: "City",
    datalistOptions: ["Karachi", "Lahore", "Islamabad", "Sukkur"],
  },
  {
    id: "technology",
    label: "Technology",
    datalistOptions: [
      "Python",
      "Java",
      "C#",
      "Ruby",
      "PHP",
      "Go",
      "Rust",
      "Swift",
      "Kotlin",
      "HTML",
      "CSS",
      "Sass",
      "React",
      "Angular",
      "Vue.js",
      "Node.js",
      "Django",
      "Flask",
      "Spring Boot",
      "Laravel",
    ],
  },
];

export const SortOptions = {
  id: "sort",
  label: "Select",
  datalistOptions: ["Rank", "Name", "Country", "City", "Weight"],
};

export const primaryColor = "#64D894";

export const currentUser = {
  id: 1,
  name: "Current User",
  country: "United States",
  city: "New York",
  weight: 120000.5,
};

export const tableData = [
  {
    id: 1,
    name: "Alice Johnson",
    country: "United States",
    city: "New York",
    weight: 120000.5,
  },
  {
    id: 2,
    name: "David Smith",
    country: "Australia",
    city: "Sydney",
    weight: 115500.0,
  },
  {
    id: 3,
    name: "Ravi Patel",
    country: "India",
    city: "Mumbai",
    weight: 113200.2,
  },
  {
    id: 4,
    name: "Laura Chen",
    country: "China",
    city: "Beijing",
    weight: 110750.3,
  },
  {
    id: 5,
    name: "Carlos Garcia",
    country: "Mexico",
    city: "Mexico City",
    weight: 108300.8,
  },
  {
    id: 6,
    name: "Emma Brown",
    country: "United Kingdom",
    city: "London",
    weight: 106500.4,
  },
  {
    id: 7,
    name: "Ahmed Khan",
    country: "Pakistan",
    city: "Karachi",
    weight: 104000.7,
  },
  {
    id: 8,
    name: "Olivia Davis",
    country: "Canada",
    city: "Toronto",
    weight: 102250.9,
  },
  {
    id: 9,
    name: "Hiroshi Tanaka",
    country: "Japan",
    city: "Tokyo",
    weight: 99800.6,
  },
  {
    id: 10,
    name: "Sophia Lopez",
    country: "Brazil",
    city: "São Paulo",
    weight: 98500.1,
  },
  {
    id: 11,
    name: "Mia Müller",
    country: "Germany",
    city: "Berlin",
    weight: 97200.0,
  },
  {
    id: 12,
    name: "Liam Anderson",
    country: "New Zealand",
    city: "Auckland",
    weight: 95500.8,
  },
  {
    id: 13,
    name: "Ethan Lee",
    country: "South Korea",
    city: "Seoul",
    weight: 93500.3,
  },
  {
    id: 14,
    name: "Isabella Rossi",
    country: "Italy",
    city: "Rome",
    weight: 91000.2,
  },
  {
    id: 15,
    name: "Lucas Dubois",
    country: "France",
    city: "Paris",
    weight: 89000.5,
  },
  {
    id: 16,
    name: "Chloe White",
    country: "South Africa",
    city: "Cape Town",
    weight: 87000.0,
  },
  {
    id: 17,
    name: "Noah Evans",
    country: "Australia",
    city: "Melbourne",
    weight: 86000.3,
  },
  {
    id: 18,
    name: "Aria Kim",
    country: "South Korea",
    city: "Busan",
    weight: 84500.7,
  },
  {
    id: 19,
    name: "James Wilson",
    country: "United States",
    city: "Los Angeles",
    weight: 83000.4,
  },
  {
    id: 20,
    name: "Sofia Gonzalez",
    country: "Spain",
    city: "Madrid",
    weight: 81000.1,
  },
];

export const userData = {
  image: "https://avatars.githubusercontent.com/u/350947?v=4",
  name: "Drew Noakes",
  country: "Australia",
  city: "Melbourne",
};

export const scoreAndbadges = {
  score: {
    score: "59,520.7",
    rank: "Top 1%",
    repos: "231",
    events: "1364",
  },
  badges: [
    {
      name: "C#",
      imgLink: "https://icon-widget.codersrank.io/api/C%23",
      level: "Top 1",
      role: "Developer",
      country: "Australia",
    },
    {
      name: "C++",
      imgLink: "https://icon-widget.codersrank.io/api/C%2B%2B",
      level: "Top 1",
      role: "Developer",
      country: "Australia",
    },
    {
      name: "JavaScript",
      imgLink: "https://icon-widget.codersrank.io/api/JavaScript",
      level: "Top 1",
      role: "Developer",
      country: "Australia",
    },
  ],
};

export const technologies = [
  {
    name: "Wpf",
    rank: "Top 0.01%",
    imageUrl: "https://icon-widget.codersrank.io/api/Wpf",
  },
  {
    name: "NodeJS",
    rank: "Top 0.01%",
    imageUrl: "https://icon-widget.codersrank.io/api/NodeJS",
  },
  {
    name: "Echo",
    rank: "Top 0.01%",
    imageUrl: "https://icon-widget.codersrank.io/api/Echo",
  },
  {
    name: "Gulp",
    rank: "Top 0.04%",
    imageUrl: "https://icon-widget.codersrank.io/api/Gulp",
  },
  {
    name: "mongoose",
    rank: "Top 45%",
    imageUrl: "https://icon-widget.codersrank.io/api/mongoose",
  },
  {
    name: "ReactJS",
    rank: "Top 90%",
    imageUrl: "https://icon-widget.codersrank.io/api/ReactJS",
  },
  {
    name: "JUnit",
    rank: "Top 42%",
    imageUrl: "https://icon-widget.codersrank.io/api/JUnit",
  },
  {
    name: "NUnit",
    rank: "Top 55%",
    imageUrl: "https://icon-widget.codersrank.io/api/NUnit",
  },
  {
    name: "Unity3D",
    rank: "Top 76%",
    imageUrl: "https://icon-widget.codersrank.io/api/Unity3D",
  },
];

export const languages = [
  {
    name: "C#",
    experience: "6,955",
    rankWorldwide: "0.01",
    totalWorldwide: "74K",
    scopeWorldwide: "Worldwide",
    rankLocal: "2",
    totalLocal: "68",
    scopeLocal: "Australia",
    imageUrl: "https://icon-widget.codersrank.io/api/C%23",
  },
  {
    name: "JavaScript",
    experience: "5,909",
    rankWorldwide: "0.01",
    totalWorldwide: "278K",
    scopeWorldwide: "Worldwide",
    rankLocal: "1",
    totalLocal: "195",
    scopeLocal: "Australia",
    imageUrl: "https://icon-widget.codersrank.io/api/NodeJS",
  },
  {
    name: "HTML",
    experience: "1,694",
    rankWorldwide: "0.01",
    totalWorldwide: "291K",
    scopeWorldwide: "Worldwide",
    rankLocal: "1",
    totalLocal: "190",
    scopeLocal: "Australia",
    imageUrl: "https://icon-widget.codersrank.io/api/HTML",
  },
  {
    name: "Kotlin",
    experience: "1,676",
    rankWorldwide: "0.01",
    totalWorldwide: "26K",
    scopeWorldwide: "Worldwide",
    rankLocal: "5",
    totalLocal: "22",
    scopeLocal: "Australia",
    imageUrl: "https://icon-widget.codersrank.io/api/Kotlin",
  },
  {
    name: "Java",
    experience: "765",
    rankWorldwide: "0.2",
    totalWorldwide: "130K",
    scopeWorldwide: "Worldwide",
    rankLocal: "4",
    totalLocal: "89",
    scopeLocal: "Australia",
    imageUrl: "https://icon-widget.codersrank.io/api/Java",
  },
  {
    name: "C++",
    experience: "808",
    rankWorldwide: "0.09",
    totalWorldwide: "87K",
    scopeWorldwide: "Worldwide",
    rankLocal: "2",
    totalLocal: "79",
    scopeLocal: "Australia",
    imageUrl: "https://icon-widget.codersrank.io/api/C%2B%2B",
  },
];
